#:schema node_modules/wrangler/config-schema.json
name = "next-cf"
main = ".open-next/worker.js"

compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Assets used for files and cache priming.
assets = { directory = ".open-next/assets", binding = "ASSETS" }
