import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by about",
};

export default function Page() {
  return (
    <>
      <section>
        <div className="max-w-screen-lg mx-auto flex mb-6">
          <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
            Get started by editing&nbsp;
            <code className="font-mono font-bold">src/app/page.tsx</code>
          </p>
          <Link href="/">home</Link>
        </div>
      </section>
    </>
  );
}
