import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumb from "@/ui/breadcrumb";

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by about",
};

export default function Home() {
  const breadcrumbItems = [
    { href: "/", element: "Home" },
    { href: "/category/electronics", element: "Electronics" },
    {
      href: "/product/123",
      element: (
        <span>
          Product 123 with <strong>Emphasis</strong>
        </span>
      ),
    }, // JSX element with more complex content
  ];

  return (
    <>
      <Breadcrumb items={breadcrumbItems} />
      <section className="">
        <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
          <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
            Get started by editing&nbsp;
            <code className="font-mono font-bold">src/app/page.tsx</code>
          </p>
          <Link href="/">home</Link>
        </div>
      </section>
    </>
  );
}
