import Image from "next/image";
import Link from "next/link";
import { useTranslations } from "next-intl";

import type { Metadata } from "next";
import FeatureWhy from "@/components/features/feature.why";
import FeatureValues from "@/components/features/feature.values";
import HeroDefault from "@/components/heros/hero.default";
import HeroText from "@/components/heros/hero.text";
import FaqDefault from "@/components/faqs/faq.normal";
import FaqSimple from "@/components/faqs/faq.simple";
import Grid from "@/components/recommends/grid";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by homepage",
};

export default function Home() {
  const t = useTranslations("home");
  return (
    <>
      <HeroText />
      {/* <HeroDefault /> */}
      {/* <FeatureValues /> */}
      {/* <FeatureWhy /> */}
      {/* <FaqDefault /> */}
      <Grid />
      <FaqSimple />
    </>
  );
}
